version: "3.8"
name: sko-team13-dashboard
services:
  solace-ai-connector:
    container_name: solace-ai-connector
    build:
      context: ./solace-ai
      dockerfile: ./Dockerfile
    env_file: ./solace-ai/.env
    volumes:
      - ./solace-ai/getting-started/qdrant_rag.yaml:/app/config/configuration.yaml
  sko-team13-dashboard:
    container_name: sko-team13-dashboard
    build:
      context: ./demothon-dashboard-vue
      dockerfile: ./Dockerfile
    env_file: demothon-dashboard-vue/.env
    ports:
      - "8080:80"
    # Only needed if you need to overrite default
    # volumes:
    # - ./demothon-dashboard-vue/dist:/usr/share/nginx/html
    # - ./demothon-dashboard-vue/nginx.conf:/etc/nginx/conf.d/default.conf
