/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AISearch: typeof import('./src/components/AISearch.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MapComponent: typeof import('./src/components/MapComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoreDetailsChart: typeof import('./src/components/StoreDetailsChart.vue')['default']
    StoreDetailsCharts: typeof import('./src/components/StoreDetailsCharts.vue')['default']
    TransactionExplorer: typeof import('./src/components/TransactionExplorer.vue')['default']
    TransactionTracker: typeof import('./src/components/TransactionTracker.vue')['default']
  }
}
